verticles:
  dao: pt.fabm.template.dao.DaoVerticle
  web: pt.fabm.multimodule.main.WebVerticle
confs:
  rest:
    ssr: true
    host: 0.0.0.0
    port: 8888
    pdir: ./frontend/dist
    #user token timeout in milliseconds 30 minutes = 30*60*1000
    user_timeout: 1800000
  dao:
    host: 0.0.0.0
    port: 8081
